### ISSUE TITLE
Ability to add metadata about a given shipment

### ISSUE THREAD

**Issue by MDrooker** [turnerlabs/harbor-ui#23]
As a user, I would like the ability to know a few things about a shipment.
1.  Who actually created it.  
Who was the last person to trigger it.  
When it was created. 
When it was last triggered
A URL field for-
Support Info URL

**Comment by donwb** [comment]
This is a great idea... do we have it scheduled for a release soon?

**Comment by donwb** [comment]
@mickeyyawn this is a great idea

**Comment by jritsema** [comment]
Fyi, there is a basic GUI that provides some of this (but it's userland, not integrated with main site).

http://harbor-audit.prod.services.ec2.dmtio.net/

We've talked about integrating it and we could provide the summary info (created date/by, last modified, etc).  Would definitely be a great feature to allow users to tag shipments with support URLs, etc.

**Comment by mickeyyawn** [comment]
Some of the audit stuff was addressed by Josh the past week.  He is working on incorporating that into the UI now.  It most addresses the who/when was the shipment triggered, and speaks to the SOX request stemming from Angie.  The support field is a different beast and will require different conversation.

**Comment by jkurz** [comment]
Yes the only thing we are missing is the ERP information that @wilsonodk is working on in this issue https://github.com/turnerlabs/harbor/issues/24
