### ISSUE TITLE
Error viewing logs

### ISSUE THREAD

**Issue by MDrooker** [turnerlabs/harbor-ui#24]
Getting - 
main.js:4309 Uncaught TypeError: self.logs.join is not a function
<img width="1862" alt="screen shot 2016-10-23 at 2 38 54 pm" src="https://cloud.githubusercontent.com/assets/6624513/19628562/99d3f09c-992e-11e6-8b9a-6574609d2a4a.png">

**Comment by wilsonodk** [comment]
Fixed
