### ISSUE TITLE
Strip Whitespace from SSL ARN

### ISSUE THREAD

**Issue by wilsonodk** [turnerlabs/harbor-ui#32]
When users cut-n-paste ARNs they may unintentionally add whitespace. Make sure to trim the strings before saving to ShipIt.

**Comment by nloadholtes** [comment]
I just opened PR #50 to try and help with this. Could't test it locally, but hopefully the code is pretty close to correct

**Comment by nloadholtes** [comment]
If there's no objection, I'm going to close the issue because the PR was merged.
