### ISSUE TITLE
Command bridge is a battery drain due to log polling

### ISSUE THREAD

**Issue by deviantintegral** [turnerlabs/harbor-ui#41]
When you pull up an instance under command bridge, the Harbor UI polls for updates to the logs. Unfortunately, this is a pretty significant battery drain, as it uses a decent amount of CPU. On my 2016 MBP, it uses 15-30% of a CPU core. Also, the polling occurs even when the log tab isn't selected, making it trickier to track down.

A few ideas for improving this:

* Use websockets to push logs instead of polling
* Slow down or stop the polling if the logs aren't visible
* Make tailing logs opt-in instead of opt-out.

<img width="1255" alt="task manager - google chrome 2017-05-16 13-59-20" src="https://cloud.githubusercontent.com/assets/255023/26121000/c01b421a-3a40-11e7-863b-709fe8844cb3.png">

**Comment by jkurz** [comment]
related to https://github.com/turnerlabs/harbor/issues/47

**Comment by wilsonodk** [comment]
We have done several fixes to resolve this issue: 

+ Log data is not pulled when not on the Logs tab
+ Polling on the Overview tab is less frequent
+ Polling on all tabs only occur while on that tab
+ Audit data is not pulled when not on the Audit tab
