### ISSUE TITLE
Adding a description field to ShipIt and Command Bridge

### ISSUE THREAD

**Issue by nloadholtes** [turnerlabs/harbor-ui#51]
There's a lot of things running in Harbor and sometimes from the name of the shipment it isn't clear what it does.

It would be cool if there was a description field where  someone could enter a small (a few hundred chars) description of the shipment.

As a default it would be really cool if Harbor could pull in the README.md file (or the first part of it) and use that as the default description.

**Comment by wilsonodk** [comment]
We have added Annotations that should be able to fulfill this. 

@nloadholtes Would it be ok if we closed this?

**Comment by nloadholtes** [comment]
Sure thing, sounds awesome!
